package software.coolstuff.springframework.owncloud.service.impl.resource;

import software.coolstuff.springframework.owncloud.service.AbstractOwncloudUserModificationServiceTest;

public abstract class AbstractOwncloudUserModificationServiceResourceTest extends AbstractOwncloudUserModificationServiceTest {

}
