package software.coolstuff.springframework.owncloud.service.impl.local;

import software.coolstuff.springframework.owncloud.service.AbstractOwncloudUserModificationServiceTest;

public abstract class AbstractLocalOwncloudUserModificationServiceTest extends AbstractOwncloudUserModificationServiceTest {

}
