== Configuration
All Services of this Spring-Boot Starter will be managed by the following http://docs.spring.io/spring-boot/docs/1.4.3.RELEASE/reference/htmlsingle/#boot-features-external-config[Configuration Parameters].
[cols="3,1*^,2,1*^,5", options="header"]
|===
| Name | mandatory | Data Type |Default | Description
| owncloud.location | true | String | - | The Location of the Owncloud Instance
| owncloud.user-service.enable-modifications | false | boolean | `false`
  | Modifications through `OwncloudUserService` and `OwncloudGroupService` are allowed/disallowed
| owncloud.resource-service.add-relative-down-path | true | boolean | `true`
  | add `..` to the List of available Owncloud-Resource within a Directory
| owncloud.resource-service.piped-stream-buffer-size | true | Integer | 8192
  | Buffer Size (in Bytes) for Content-Streaming (InputStream/OutputStream)
| owncloud.resource-service.piped-stream-uncaught-exception-log-level | true
  | LogLevel | `error` | Log Level for any uncaught Exceptions while Content-Streaming
|===

=== owncloud.location
The Configuration Parameter `owncloud.location` defines, what Backend will be used.

It can have one of the following Values:
[cols="1,1*^,10", options="header"]
|===
| starts with | modifiable | Description
| `http://` +
  `https://`   | true  | The Authentication uses the Owncloud of this Web-Address +
                         i.E.: `\https://www.example.com/owncloud`
| `classpath:` | false | Get Data of an In-Memory Owncloud Instance from a Classpath Resource
| `file:`      | true  | Get Data of an In-Memory Owncloud Instance from an external File Resource
|===

Normally you would provide the Web-Address of the Owncloud-Instance.
But for local Development or Tests it could be useful, to have an Owncloud Instance which
always behaves the same (returns the same Users, the same Groups, ...).

There you can define a XML-Resource with either `classpath:` or `file:`. +
This XML-Resource should have the following Format:
[source,xml]
.owncloud.xml
----
<owncloud>
  <users> <1>
    <user> <2>
      <username>user1</username> <3>
      <password>s3cr3t</password> <4>
      <enabled>true</enabled>
      
      <displayname>Mr. User 1</displayname> <5>
      <email>user1@example.com</email>
      
      <groups> <6>
        <group>group1</group>
        <group>group2</group>
      </groups>

      <quota>10240</quota> <7>
    </user>
    <user>
      <username>user2</username>
      <password>s3cr3t</password>
      <enabled>false</enabled>
      <displayName>Mrs. User 2</displayName>
      <email>user2@example.com</email>
    </user>
  </users>
  
  <groups> <8>
    <group>group1</group>
    <group>group2</group>
    <group>group3</group>
  </groups>
</owncloud>
----
<1> List of all existing Users
<2> The Definition of a single User
<3> Username, Password and Availability-Stats (`<enabled>`) are mandatory.
<4> unencrypted Password (because you're in local Development or Test Environment)
<5> optional Parameters
<6> Group Memberships of the User.
<7> File Quota of the User (in Bytes). If omitted the User has unlimited Quota on the File-System.
<8> All available Groups of the InMemory Owncloud Instance

NOTE: All Groups, which are referenced as a User-Membership will be checked
      when the Service starts. +
      If there are any Groups, which are not defined at the `<groups>` Section
      the Service will *fail on Startup* with an `IllegalStateException`.

So if you define the Configuration Parameter `owncloud.location` either as

* `classpath:/path/to/owncloud.xml` or
* `file:/path/to/owncloud.xml`

the Data of the provided XML-File will be read on Application Startup and resist as a
InMemory Representation used by the Services of this Spring-Boot Starter
(Authentication, UserQuery, UserModification, ...).

When you use a `file:` Resource the changed Data will be written to this Resource on a normal Shutdown
of the Application. This is useful for incremental Integration Tests.

When you use a `classpath:` Resource the changed Data will not be written. Therefor this type should be used
for local Development and/or Unit Tests.

