== UserDetails Service
Like the Authentication Provider the `OwncloudUserDetailsService` will be autoconfigured by including `owncloud-spring-boot-starter` into your Classpath.

The `OwncloudUserDetailsService` will be used by `OwncloudAuthenticationProvider` to load the UserDetails of the authenticated User. This is necessary to identify the Enabled/Disabled Status of the authenticated User.

Therefor the `OwncloudUserDetails` Object will be included into the `OwncloudAuthentication` Object and will be returned by calling `getPrincipal()`.

Because Owncloud only serves the Enabled/Disabled Status of the User the following Method will always return `true`:

* `isAccountNonExpired()`
* `isAccountNonLocked()`
* `isCredentialsNonExpired()`

Beside the normal Attributes of the Spring Security http://docs.spring.io/spring-security/site/docs/4.2.1.RELEASE/apidocs/org/springframework/security/core/userdetails/UserDetails.html[`UserDetails`] Object the `OwncloudUserDetails` Object provides the following, additional Fields:

* `getDisplayName()` ... The full Name of the User
* `getEmail()` ... The Email of the User
* `getGroups()` ... A List of Groups the User is a Member of
